version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
workflows:
  testpages:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome --spec cypress/e2e/testpages/*.cy.js
          install-browsers: true
  APItests:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --spec cypress/e2e/APItests/*.cy.js
          install-browsers: true
  elementInteractions:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --spec cypress/e2e/elementInteractions/*.cy.js
          install-browsers: true        